{
  "hash": "9e6b97cc0ea102a2eb512f909b584477",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"A3 God Dataset\"\nauthor: \"Swetha KV\"\ndate: \"2025-11-01\"\ncategories: [God]\nformat: html\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.2\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(vcd)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: grid\n\nAttaching package: 'vcd'\n\nThe following object is masked from 'package:mosaic':\n\n    mplot\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(visStatistics) # One package to test them all\n\n### Dataset from Chihara and Hesterberg's book (Second Edition)\nlibrary(resampledata)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'resampledata'\n\nThe following object is masked from 'package:datasets':\n\n    Titanic\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\nlibrary(infer)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'infer'\n\nThe following objects are masked from 'package:mosaic':\n\n    prop_test, t_test\n```\n\n\n:::\n\n```{.r .cell-code}\n## Datasets from Cetinkaya-Rundel and Hardin's book (First Edition)\nlibrary(openintro)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: airports\nLoading required package: cherryblossom\nLoading required package: usdata\n\nAttaching package: 'openintro'\n\nThe following object is masked from 'package:mosaic':\n\n    dotPlot\n\nThe following objects are masked from 'package:lattice':\n\n    ethanol, lsegments\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngod <- read.csv(\"kadavulirukanda.csv\")\nglimpse(god)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 47\nColumns: 3\n$ Name           <chr> \"Sanjana\", \"Tathasthu\", \"Vaibhav\", \"Siddharth\", \"Ashik\"…\n$ Gender         <chr> \"Female\", \"Male\", \"Male\", \"Male\", \"Male\", \"Female\", \"Fe…\n$ Believe_in_God <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"No\", \"Yes\", \"Yes\", \"No\", \"…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngod <- god%>% \n tidyr::drop_na()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisdat::vis_dat(god)\n```\n\n::: {.cell-output-display}\n![](god_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngod %>%\n  group_by(Believe_in_God) %>%\n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n# Groups:   Believe_in_God [2]\n  Believe_in_God     n\n  <chr>          <int>\n1 No                15\n2 Yes               26\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngod %>%\n  group_by(Gender) %>%\n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n# Groups:   Gender [2]\n  Gender     n\n  <chr>  <int>\n1 Female    23\n2 Male      18\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngod %>%\n  summarize(prop = mean(Believe_in_God == \"Yes\"), n = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       prop  n\n1 0.6341463 41\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngod_table <- vcd::structable(Gender ~ Believe_in_God, data = god)\ngod_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Gender Female Male\nBelieve_in_God                   \nNo                         5   10\nYes                       18    8\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngod %>%\n  gf_bar(~Believe_in_God, fill = ~Gender) %>%\n  gf_labs(\n    x = \"Believe in God\",\n    title = \"Proportion of Students saying they believe in god\"\n  )\n```\n\n::: {.cell-output-display}\n![](god_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n### Inference \n\n- The bar graph shows a moderate distribution of belief, indicating coexistence of both religious and secular perspectives among students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::binom.test(~Believe_in_God, data = god, success = \"Yes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n\ndata:  god$Believe_in_God  [with success = Yes]\nnumber of successes = 26, number of trials = 41, p-value = 0.1173\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.4693625 0.7787721\nsample estimates:\nprobability of success \n             0.6341463 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngod %>%\n  drop_na() %>%\n  specify(response = Believe_in_God, success = \"Yes\") %>%\n  generate(reps = 999, type = \"bootstrap\") %>%\n  calculate(stat = \"prop\") %>%\n  get_ci(level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1    0.463    0.780\n```\n\n\n:::\n:::\n\n\n# Conlcusion\n\n### Hypothesis\n\nNumerical hypothesis: The proportion of students that believe in God is equal to 0.5 (no difference and equally to believe and disbelieve).\n\nAlternative hypothesis: The proportion of students that believe in God is not equal to 0.5 (there is a difference between believe and disbelieve).\n\n### Inference\n\n- Since the p-value (0.1173) > 0.05, we fail to reject the null hypothesis.\n\n- There isn’t strong statistical evidence that the proportion of students who believe in God differs significantly from 50%.\n\n- The sample proportion (63%) does lean higher than 0.5, which means tendency toward belief that become significant.\n\n- The 95% confidence interval (0.469 to 0.779) means we are 95% confident that the true population proportion of students who believe in God lies between 46.9% and 77.9%.\n\n- Since 0.5 (the neutral value) lies within this interval, we can’t claim a significant deviation from 50%.\n\n- The unequal gender sample (23 female, 18 male) have slightly biased the overall proportion upward because the graph is showing that females tend to express higher belief rates. A gender-balanced sample might give us a slightly lower or more neutral proportion.\n\n",
    "supporting": [
      "god_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}