{
  "hash": "91f636b095f337066962d87480e5c14b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"A3 Tattoo Dataset\"\nauthor: \"Swetha KV\"\ndate: \"2025-10-31\"\ncategories: [A3]\nformat: html\n---\n# Do tattoos make people look attractive or not?\n\n## Setting up R Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.2\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(vcd)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: grid\n\nAttaching package: 'vcd'\n\nThe following object is masked from 'package:mosaic':\n\n    mplot\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(visStatistics)\nlibrary(resampledata)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'resampledata'\n\nThe following object is masked from 'package:datasets':\n\n    Titanic\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\nlibrary(infer)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'infer'\n\nThe following objects are masked from 'package:mosaic':\n\n    prop_test, t_test\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(openintro)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: airports\nLoading required package: cherryblossom\nLoading required package: usdata\n\nAttaching package: 'openintro'\n\nThe following object is masked from 'package:mosaic':\n\n    dotPlot\n\nThe following objects are masked from 'package:lattice':\n\n    ethanol, lsegments\n```\n\n\n:::\n:::\n\n\n## Read Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntattoo <- read.csv(\"tattoo.csv\")\nglimpse(tattoo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 40\nColumns: 3\n$ Name              <chr> \"Aadya\", \"Abhinav\", \"Aditya\", \"Akash\", \"Amit\", \"Amog…\n$ Gender            <chr> \"F\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"F\", \"M…\n$ Tattoo_Attractive <chr> \"Yes\", \"Yes\", \"No\", \"Yes\", \"No\", \"Yes\", \"Yes\", \"Yes\"…\n```\n\n\n:::\n:::\n\n\n## View Missing Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisdat::vis_dat(tattoo)\n```\n\n::: {.cell-output-display}\n![](tattooattraction_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n## Summerise: Examine Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntattoo %>% count(Tattoo_Attractive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tattoo_Attractive  n\n1                No 10\n2               Yes 30\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntattoo %>% count(Gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Gender  n\n1      F 20\n2      M 20\n```\n\n\n:::\n:::\n\n\n## Data Munging\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntattoo_modified <- tattoo %>%\n  dplyr::select(Gender, Tattoo_Attractive) %>%\n  tidyr::drop_na(c(Gender, Tattoo_Attractive )) %>%\n  mutate(\n    Gender = factor(Gender,\n                    levels = c(\"F\", \"M\"),\n                    labels = c(\"Female\", \"Male\")\n    ),\n    Tattoo_Attractive = factor(Tattoo_Attractive,\n                              levels = c(\"Yes\", \"No\"),\n                              labels = c(\"Yes\", \"No\")\n    )\n  )\n\nglimpse(tattoo_modified)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 40\nColumns: 2\n$ Gender            <fct> Female, Male, Male, Male, Male, Male, Male, Male, Ma…\n$ Tattoo_Attractive <fct> Yes, Yes, No, Yes, No, Yes, Yes, Yes, Yes, No, Yes, …\n```\n\n\n:::\n:::\n\n\n## Chi Sqaure Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontingency_table <- vcd::structable(Gender ~ Tattoo_Attractive,\n  data = tattoo_modified\n)\ncontingency_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Gender Female Male\nTattoo_Attractive                   \nYes                          15   15\nNo                            5    5\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngss_vcd_table <- vcd::structable(Gender ~ Tattoo_Attractive, data = tattoo_modified)\ngss_vcd_table %>%\n  vcd::mosaic(\n    gp = shading_hsv, direction = \"v\",\n    main = \"Tattoo Attraction by Gender Mosaic Chart\",\n    legend = TRUE,\n    labeling = labeling_border(\n      varnames = c(\"F\", \"F\"),  # Adjusts variable name labels\n      rot_labels = c(90, 0, 0, 0),  # Rotates top-side labels\n      just_labels = c(\n        \"left\",   # Top side\n        \"left\",   # Right side\n        \"left\",   # Bottom side\n        \"right\"   # Left side\n      )\n    )\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in legend(residuals, gpfun, residuals_type): All residuals are zero.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](tattooattraction_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n### Inference\n\n- The chart and test results strongly suggest there is no association between gender and tattoo attraction in your dataset.\n\n- Statistically, the proportions of Yes/No responses for tattoo attraction are about the same for both males and females.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Somewhat strange notation with visstat\nchisq_visstat <- visstat(\n  x = tattoo_modified, # dataframe\n  y = \"Gender\", # y variable\n  \"Tattoo_Attractive\"\n) # x variables\n```\n\n::: {.cell-output-display}\n![](tattooattraction_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in legend(residuals, gpfun, residuals_type): All residuals are zero.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](tattooattraction_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n\n```{.r .cell-code}\nchisq_visstat %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSummary of visstat object\n\n--- Named components ---\n [1] \"statistic\"    \"parameter\"    \"p.value\"      \"method\"       \"data.name\"   \n [6] \"observed\"     \"expected\"     \"residuals\"    \"stdres\"       \"mosaic_stats\"\n\n--- Contents ---\n\n$statistic:\nX-squared \n        0 \n\n$parameter:\ndf \n 1 \n\n$p.value:\n[1] 1\n\n$method:\n[1] \"Pearson's Chi-squared test\"\n\n$data.name:\n[1] \"counts\"\n\n$observed:\n      Gender\ngroups Female Male\n   Yes     15   15\n   No       5    5\n\n$expected:\n      Gender\ngroups Female Male\n   Yes     15   15\n   No       5    5\n\n$residuals:\n      Gender\ngroups Female Male\n   Yes      0    0\n   No       0    0\n\n$stdres:\n      Gender\ngroups Female Male\n   Yes      0    0\n   No       0    0\n\n$mosaic_stats:\n                  Gender Female Male\nTattoo_Attractive                   \nYes                          15   15\nNo                            5    5\n\n--- Attributes ---\n$plot_paths\ncharacter(0)\n```\n\n\n:::\n:::\n\n\n### Hypothesis\n\nNull Hypothesis: There is no association between gender and finding tattoos attractive.\n\nAlternative Hypothesis: Null Hypothesis is true \n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq_visstat$observed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Gender\ngroups Female Male\n   Yes     15   15\n   No       5    5\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq_visstat$expected\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Gender\ngroups Female Male\n   Yes     15   15\n   No       5    5\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq_visstat$stdres\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Gender\ngroups Female Male\n   Yes      0    0\n   No       0    0\n```\n\n\n:::\n:::\n\nNeed more samples!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(tattoo_modified$Gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFemale   Male \n    20     20 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(tattoo_modified$Tattoo_Attractive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nYes  No \n 30  10 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontingency_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  Gender Female Male\nTattoo_Attractive                   \nYes                          15   15\nNo                            5    5\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontingency_table <- table(tattoo_modified$Gender, tattoo_modified$Tattoo_Attractive)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxq_test_object <- xchisq.test(contingency_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  x\nX-squared = 0, df = 1, p-value = 1\n\n   15        5   \n(15.00)  ( 5.00) \n [0.00]   [0.00] \n <0.00>   <0.00> \n   \n   15        5   \n(15.00)  ( 5.00) \n [0.00]   [0.00] \n <0.00>   <0.00> \n   \nkey:\n\tobserved\n\t(expected)\n\t[contribution to X-squared]\n\t<Pearson residual>\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxq_test_object %>%\n  broom::tidy() %>%\n  select(statistic) %>%\n  as.numeric() -> X_squared_observed\nX_squared_observed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- 1\nX_squared_observed <- 0\nX_squared_critical <- qchisq(0.95, df)\n\nmosaic::xqchisq(\n  p = 0.95, df = df,\n  return = c(\"plot\"), verbose = FALSE,\n  system = \"gg\"\n) %>%\n  gf_labs(\n    x = \"F value\", title = \"Critical and Observed Chi-Square Values\"\n  ) %>%\n  gf_vline(\n    xintercept = X_squared_observed,\n    color = \"red\", linewidth = 1\n  ) %>%\n  gf_vline(\n    xintercept = X_squared_critical,\n    color = \"dodgerblue\",\n    linewidth = 1\n  ) %>%\n  gf_annotate(\n    x = X_squared_observed - 2.5, y = 0.15,\n    geom = \"label\", label = \"Observed\\nChi-Square\",\n    fill = \"red\", alpha = 0.3\n  ) %>%\n  gf_annotate(\"curve\", X_squared_observed - 2.5,\n    y = 0.135, yend = 0.10,\n    xend = X_squared_observed - 0.5,\n    linewidth = 0.5, curvature = 0.3,\n    arrow = arrow(length = unit(0.25, \"cm\"))\n  ) %>%\n  gf_annotate(\n    # ***MODIFIED: Changed x from + 2.5 to + 1.5***\n    x = X_squared_critical + 1.5, y = 0.15,\n    geom = \"label\", label = \"Critical\\nChi-Square\",\n    fill = \"lightblue\"\n  ) %>%\n  gf_annotate(\"curve\", X_squared_critical + 1.5,\n    y = 0.135, yend = 0.10,\n    xend = X_squared_critical + 0.25,\n    linewidth = 0.5, curvature = -0.3,\n    arrow = arrow(length = unit(0.25, \"cm\"))\n  ) %>%\n  gf_refine(\n    scale_y_continuous(expand = expansion(add = c(0, 0.01))),\n    scale_x_continuous(expand = expansion(add = c(3, 2)))\n  )\n```\n\n::: {.cell-output-display}\n![](tattooattraction_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n### Inference\n\n- This shows the expected frequency of different Chi-Square values under the null hypothesis (there is no significant relationship).\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntattoo_vcd_table <- vcd::structable(Tattoo_Attractive ~ Gender,\n  data = tattoo_modified\n)\n\nvcd::mosaic(tattoo_vcd_table,\n  gp = shading_max, legend = TRUE, direction = \"v\",\n  labeling = labeling_border(\n    varnames = c(\"F\", \"F\"),\n    rot_labels = c(90, 0, 0, 0),\n    just_labels = c(\n      \"left\",\n      \"left\",\n      \"left\",\n      \"right\"\n    )\n  )\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in legend(residuals, gpfun, residuals_type): All residuals are zero.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](tattooattraction_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n\n```{.r .cell-code}\nvcd::mosaic(tattoo_vcd_table,\n  type = \"expected\", gp = shading_max, legend = TRUE, direction = \"v\",\n  labeling = labeling_border(\n    varnames = c(\"F\", \"F\"),\n    rot_labels = c(90, 0, 0, 0),\n    just_labels = c(\n      \"left\",\n      \"left\",\n      \"left\",\n      \"right\"\n    )\n  )\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in legend(residuals, gpfun, residuals_type): All residuals are zero.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](tattooattraction_files/figure-html/unnamed-chunk-19-2.png){width=672}\n:::\n\n```{.r .cell-code}\nvcd::assoc(tattoo_vcd_table,\n  gp = shading_max, legend = TRUE, direction = \"v\",\n  labeling = labeling_border(\n    varnames = c(\"F\", \"F\"),\n    rot_labels = c(90, 0, 0, 0),\n    just_labels = c(\n      \"left\",\n      \"left\",\n      \"left\",\n      \"right\"\n    )\n  )\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in legend(residuals, gpfun, residuals_type): All residuals are zero.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](tattooattraction_files/figure-html/unnamed-chunk-19-3.png){width=672}\n:::\n:::\n\n\n### Inference\n\n- The Chi-Square test was conducted to check the relationship between gender and whether people find tattoos attractive.\n\n- The observed frequencies (Female: 15 Yes, 5 No; Male: 15 Yes, 5 No) are same to the expected frequencies.\n\n- The Chi-Square value = 0, with 1 degree of freedom and a p-value = 1.0.\n\n- Since the p-value (1.0) is greater than 0.05. This means there is no association between gender and perception of tattoo attractiveness.\n\n- Both males and females responded in exactly the same way, showing no variation in opinion.\n\n## Proportion Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntattoo_modified %>%\n  group_by(Tattoo_Attractive) %>%\n  count()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n# Groups:   Tattoo_Attractive [2]\n  Tattoo_Attractive     n\n  <fct>             <int>\n1 Yes                  30\n2 No                   10\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntattoo_modified_clean <- tattoo_modified %>%\n  drop_na(Tattoo_Attractive)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntattoo_modified_clean %>%\n  count(Tattoo_Attractive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tattoo_Attractive  n\n1               Yes 30\n2                No 10\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntattoo_modified_clean %>%\n  summarize(prop = mean(Tattoo_Attractive == \"Yes\"), n = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  prop  n\n1 0.75 40\n```\n\n\n:::\n:::\n\n\n### Inference\n- The test result confirms if this percentage is significantly above 50%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntattoo_modified_clean %>%\n  drop_na() %>%\n  gf_bar(~Tattoo_Attractive, fill = ~Gender) %>%\n  gf_labs(\n    x = \"Found tattoos attractive?\",\n    title = \"Proportion of Students Finding Tattoos Attractive\"\n  )\n```\n\n::: {.cell-output-display}\n![](tattooattraction_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n### Inference\n\n- Majority of them find tattoos attractive and it's equally spread out\n\n- Again no association between gender and perception of tattoo attractiveness\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::binom.test(~Tattoo_Attractive, data = tattoo_modified_clean, success = \"Yes\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\n\ndata:  tattoo_modified_clean$Tattoo_Attractive  [with success = Yes]\nnumber of successes = 30, number of trials = 40, p-value = 0.002221\nalternative hypothesis: true probability of success is not equal to 0.5\n95 percent confidence interval:\n 0.5880380 0.8730852\nsample estimates:\nprobability of success \n                  0.75 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaic::binom.test(~Tattoo_Attractive, data = tattoo_modified_clean, success = \"Yes\") %>%\n  broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  estimate statistic p.value parameter conf.low conf.high alternative\n     <dbl>     <dbl>   <dbl>     <dbl>    <dbl>     <dbl> <chr>      \n1     0.75        30 0.00222        40    0.588     0.873 two.sided  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntattoo_modified_clean %>%\n  drop_na() %>%\n  specify(response = Tattoo_Attractive, success = \"Yes\") %>%\n  generate(reps = 999, type = \"bootstrap\") %>%\n  calculate(stat = \"prop\") %>%\n  get_ci(level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  lower_ci upper_ci\n     <dbl>    <dbl>\n1      0.6    0.875\n```\n\n\n:::\n:::\n\n\n### Inference\n\n- A sample proportion test was conducted to determine if the proportion of students who find tattoos attractive differs significantly from 0.5 (i.e., 50%).\n\n- Out of 40 students, 30 (75%) said they find tattoos attractive.\n\n- The sample proportion (p) = 0.75.\n\n- The p-value obtained from the test is 0.0022, which is less than 0.05. This means that the proportion of students who find tattoos attractive is significantly different from 50%.\n\n- The 95% confidence interval (0.588 to 0.873) indicates that the true proportion of students who find tattoos attractive likely falls between 59% and 87%.\n\n## Conclusion\n\n- The Chi sqaure result is Not Statistically Significant. We Fail to Reject the Null Hypothesis.\n\n- However, because the sample size is small (only 40 participants), the test may not capture real-world differences. A larger sample is needed to draw stronger and more reliable conclusions.\n\n- For now, we can only conclude that within this limited sample, gender has no impact on tattoo attractiveness.\n\n- But ",
    "supporting": [
      "tattooattraction_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}