{
  "hash": "fabc4d76a7b1cce907963b5193a1e7d6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ufo\"\nformat: html\n---\n# 2. UFO Data set\n\n## Setting up R Packages\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.2\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula) \nlibrary(skimr) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(janitor) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'janitor'\n\nThe following objects are masked from 'package:stats':\n\n    chisq.test, fisher.test\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(naniar) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'naniar'\n\nThe following object is masked from 'package:skimr':\n\n    n_complete\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(visdat) \nlibrary(tinytable) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'tinytable'\n\nThe following object is masked from 'package:ggplot2':\n\n    theme_void\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(DT) \nlibrary(crosstable) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'crosstable'\n\nThe following object is masked from 'package:purrr':\n\n    compact\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(RColorBrewer)\nlibrary(naniar)\nlibrary(tidyr)\nlibrary(dplyr) \n```\n:::\n\n## Read Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings <- readr::read_csv(\"https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2019/2019-06-25/ufo_sightings.csv\") %>% \n  janitor::clean_names(case = \"snake\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 80332 Columns: 11\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (8): date_time, city_area, state, country, ufo_shape, described_encounte...\ndbl (3): encounter_length, latitude, longitude\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n## Examine Data\n\n::: {.cell}\n\n```{.r .cell-code}\nbase::names(ufo_sightings)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"date_time\"                  \"city_area\"                 \n [3] \"state\"                      \"country\"                   \n [5] \"ufo_shape\"                  \"encounter_length\"          \n [7] \"described_encounter_length\" \"description\"               \n [9] \"date_documented\"            \"latitude\"                  \n[11] \"longitude\"                 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndplyr::glimpse(ufo_sightings)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 80,332\nColumns: 11\n$ date_time                  <chr> \"10/10/1949 20:30\", \"10/10/1949 21:00\", \"10…\n$ city_area                  <chr> \"san marcos\", \"lackland afb\", \"chester (uk/…\n$ state                      <chr> \"tx\", \"tx\", NA, \"tx\", \"hi\", \"tn\", NA, \"ct\",…\n$ country                    <chr> \"us\", NA, \"gb\", \"us\", \"us\", \"us\", \"gb\", \"us…\n$ ufo_shape                  <chr> \"cylinder\", \"light\", \"circle\", \"circle\", \"l…\n$ encounter_length           <dbl> 2700, 7200, 20, 20, 900, 300, 180, 1200, 18…\n$ described_encounter_length <chr> \"45 minutes\", \"1-2 hrs\", \"20 seconds\", \"1/2…\n$ description                <chr> \"This event took place in early fall around…\n$ date_documented            <chr> \"4/27/2004\", \"12/16/2005\", \"1/21/2008\", \"1/…\n$ latitude                   <dbl> 29.88306, 29.38421, 53.20000, 28.97833, 21.…\n$ longitude                  <dbl> -97.941111, -98.581082, -2.916667, -96.6458…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase::dim(ufo_sightings)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 80332    11\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nutils::str(ufo_sightings)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspc_tbl_ [80,332 × 11] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ date_time                 : chr [1:80332] \"10/10/1949 20:30\" \"10/10/1949 21:00\" \"10/10/1955 17:00\" \"10/10/1956 21:00\" ...\n $ city_area                 : chr [1:80332] \"san marcos\" \"lackland afb\" \"chester (uk/england)\" \"edna\" ...\n $ state                     : chr [1:80332] \"tx\" \"tx\" NA \"tx\" ...\n $ country                   : chr [1:80332] \"us\" NA \"gb\" \"us\" ...\n $ ufo_shape                 : chr [1:80332] \"cylinder\" \"light\" \"circle\" \"circle\" ...\n $ encounter_length          : num [1:80332] 2700 7200 20 20 900 300 180 1200 180 120 ...\n $ described_encounter_length: chr [1:80332] \"45 minutes\" \"1-2 hrs\" \"20 seconds\" \"1/2 hour\" ...\n $ description               : chr [1:80332] \"This event took place in early fall around 1949-50. It occurred after a Boy Scout meeting in the Baptist Church\"| __truncated__ \"1949 Lackland AFB&#44 TX.  Lights racing across the sky &amp; making 90 degree turns on a dime.\" \"Green/Orange circular disc over Chester&#44 England\" \"My older brother and twin sister were leaving the only Edna theater at about 9 PM&#44...we had our bikes and I \"| __truncated__ ...\n $ date_documented           : chr [1:80332] \"4/27/2004\" \"12/16/2005\" \"1/21/2008\" \"1/17/2004\" ...\n $ latitude                  : num [1:80332] 29.9 29.4 53.2 29 21.4 ...\n $ longitude                 : num [1:80332] -97.94 -98.58 -2.92 -96.65 -157.8 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   date_time = col_character(),\n  ..   city_area = col_character(),\n  ..   state = col_character(),\n  ..   country = col_character(),\n  ..   ufo_shape = col_character(),\n  ..   encounter_length = col_double(),\n  ..   described_encounter_length = col_character(),\n  ..   description = col_character(),\n  ..   date_documented = col_character(),\n  ..   latitude = col_double(),\n  ..   longitude = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n\n\n:::\n:::\n\n## Viewing Missing Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisdat::vis_dat(ufo_sightings)\n```\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisdat::vis_miss(ufo_sightings)\n```\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n## Removing Missing Data\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_withoutNA <- ufo_sightings %>% drop_na()\nglimpse(ufo_sightings_withoutNA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 66,516\nColumns: 11\n$ date_time                  <chr> \"10/10/1949 20:30\", \"10/10/1956 21:00\", \"10…\n$ city_area                  <chr> \"san marcos\", \"edna\", \"kaneohe\", \"bristol\",…\n$ state                      <chr> \"tx\", \"tx\", \"hi\", \"tn\", \"ct\", \"al\", \"fl\", \"…\n$ country                    <chr> \"us\", \"us\", \"us\", \"us\", \"us\", \"us\", \"us\", \"…\n$ ufo_shape                  <chr> \"cylinder\", \"circle\", \"light\", \"sphere\", \"d…\n$ encounter_length           <dbl> 2700, 20, 900, 300, 1200, 180, 120, 300, 18…\n$ described_encounter_length <chr> \"45 minutes\", \"1/2 hour\", \"15 minutes\", \"5 …\n$ description                <chr> \"This event took place in early fall around…\n$ date_documented            <chr> \"4/27/2004\", \"1/17/2004\", \"1/22/2004\", \"4/2…\n$ latitude                   <dbl> 29.88306, 28.97833, 21.41806, 36.59500, 41.…\n$ longitude                  <dbl> -97.94111, -96.64583, -157.80361, -82.18889…\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ufo_sightings_withoutNA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  date_time          city_area            state             country         \n Length:66516       Length:66516       Length:66516       Length:66516      \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n  ufo_shape         encounter_length   described_encounter_length\n Length:66516       Min.   :       0   Length:66516              \n Class :character   1st Qu.:      30   Class :character          \n Mode  :character   Median :     180   Mode  :character          \n                    Mean   :    6573                             \n                    3rd Qu.:     600                             \n                    Max.   :82800000                             \n description        date_documented       latitude        longitude      \n Length:66516       Length:66516       Min.   :-37.81   Min.   :-176.66  \n Class :character   Class :character   1st Qu.: 34.20   1st Qu.:-114.18  \n Mode  :character   Mode  :character   Median : 39.25   Median : -89.60  \n                                       Mean   : 38.71   Mean   : -95.29  \n                                       3rd Qu.: 42.34   3rd Qu.: -80.40  \n                                       Max.   : 72.70   Max.   : 153.10  \n```\n\n\n:::\n:::\n\n\n# Understanding the Data\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(ufo_sightings_withoutNA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"date_time\"                  \"city_area\"                 \n [3] \"state\"                      \"country\"                   \n [5] \"ufo_shape\"                  \"encounter_length\"          \n [7] \"described_encounter_length\" \"description\"               \n [9] \"date_documented\"            \"latitude\"                  \n[11] \"longitude\"                 \n```\n\n\n:::\n:::\n\n\nThe column described_encounter_length and encounter_length both contain similar information, but encounter_length is more cleaner and easier to work with for analysis. Therefore, we will remove the redundant column.\n\nThe columns country, ufo_shape, and state may contain inconsistent or repeated entries — for example, light, Light, lights. We will examine all unique values in these columns to identify and correct such inconsistencies.\n\nAdditionally, the date_documented column could reveal interesting patterns, such as multiple UFO sightings on the same date, which we will explore.\n\n## Removing column described_encounter_length\n\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_new <- ufo_sightings_withoutNA %>%\n  select(-described_encounter_length)\n\nglimpse(ufo_sightings_new)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 66,516\nColumns: 10\n$ date_time        <chr> \"10/10/1949 20:30\", \"10/10/1956 21:00\", \"10/10/1960 2…\n$ city_area        <chr> \"san marcos\", \"edna\", \"kaneohe\", \"bristol\", \"norwalk\"…\n$ state            <chr> \"tx\", \"tx\", \"hi\", \"tn\", \"ct\", \"al\", \"fl\", \"ca\", \"nc\",…\n$ country          <chr> \"us\", \"us\", \"us\", \"us\", \"us\", \"us\", \"us\", \"us\", \"us\",…\n$ ufo_shape        <chr> \"cylinder\", \"circle\", \"light\", \"sphere\", \"disk\", \"dis…\n$ encounter_length <dbl> 2700, 20, 900, 300, 1200, 180, 120, 300, 180, 1800, 1…\n$ description      <chr> \"This event took place in early fall around 1949-50. …\n$ date_documented  <chr> \"4/27/2004\", \"1/17/2004\", \"1/22/2004\", \"4/27/2007\", \"…\n$ latitude         <dbl> 29.88306, 28.97833, 21.41806, 36.59500, 41.11750, 33.…\n$ longitude        <dbl> -97.94111, -96.64583, -157.80361, -82.18889, -73.4083…\n```\n\n\n:::\n:::\n\n\n## Visualising Data\n\n### 1. UFO Sightings throughout the years (date)\n\nLooking at ufo sightings found on the same date.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_repeated <- ufo_sightings_new %>%\n  group_by(date_documented) %>%       \n  summarise(count = n()) %>%          \n  filter(count > 1)  \n\nglimpse(ufo_sightings_repeated)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 314\nColumns: 2\n$ date_documented <chr> \"1/10/2009\", \"1/10/2014\", \"1/11/2002\", \"1/11/2005\", \"1…\n$ count           <int> 878, 513, 230, 127, 465, 133, 340, 138, 351, 98, 74, 1…\n```\n\n\n:::\n:::\n\nThe above piece of code tells us that there are 314 unique dates where data was documented - dataset that had at least one sighting.\n\nSince the there will be countless data stored in each date, we plotted a graph where x as a timeline with the range of the first date data was collected and the latest and the y-axis with a count function inbuilt in ggformula.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_new %>%\n  count(date_documented, name = \"count\") %>%\n  mutate(date_documented = mdy(date_documented)) %>%\n  gf_line(count ~ date_documented)\n```\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nSeeing this graph we can see a stark differences around 2010, there is a high point and low point and its very erratic. Lets isolate the high and low points of the graph alone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_new%>%\n  count(date_documented, name = \"count\") %>%\n  mutate(date_documented = mdy(date_documented)) %>%\n  gf_point(count ~ date_documented,\n           color = \"red\", size = 1.5) %>%\n  gf_labs(\n    title = \"Reported UFO Sightings per Date\",\n    x = \"Date\",\n    y = \"Number of Sightings\"\n  )\n```\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\nThis tells us that the data with lesser number of sightings is significantly more than data with higher number of sightings which makes intuitive sense. Lets make this more useful by making a gradient within the graph. Lowest - blue and highest - red\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(RColorBrewer)\n\nufo_sightings_new %>%\n  count(date_documented, name = \"count\") %>%\n  mutate(date_documented = mdy(date_documented)) %>%\n  gf_point(count ~ date_documented, color = ~count, size = 1.5) %>%\n  gf_refine(scale_color_gradient(low = \"blue\", high = \"red\")) %>%\n  gf_labs(\n    title = \"Reported UFO Sightings per Date\",\n    x = \"Date\",\n    y = \"Number of Sightings\",\n    color = \"Sightings Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nVisualising the graph with red points and the line graph:\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_new %>%\n  mutate(date_documented = mdy(date_documented)) %>%\n  group_by(date_documented) %>%\n  summarise(count = n()) %>%\n  gf_line(count ~ date_documented) %>%\n  gf_point(color = \"red\", size = 1) %>%\n  gf_labs(\n    title = \"Reported UFO Sightings Over Time\",\n    x = \"Date\",\n    y = \"Number of Sightings\"\n  )\n```\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\nThe graph looks very congested so faceting it would give more precise graphs. Lets facet it into 8 different segments.\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_new %>%\n  mutate(date_documented = mdy(date_documented),\n         segment = ntile(date_documented, 8)) %>%\n  group_by(date_documented, segment) %>%\n  summarise(count = n(), .groups = \"drop\") %>%\n  gf_line(count ~ date_documented) %>%\n  gf_point(color = \"red\", size = 1) %>%\n  gf_facet_wrap(~segment, scales = \"free_x\") %>%\n  gf_labs(\n    title = \"Reported UFO Sightings Over Time\",\n    x = \"Date\",\n    y = \"Number of Sightings\"\n  )\n```\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\nIt would be nice to see the highest and lowest point throughout the years. Lets try doing that:\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_highest_lowest <-ufo_sightings_new %>%\n  mutate(date_documented = mdy(date_documented)) %>%\n  group_by(date_documented) %>%\n  summarise(count = n(), .groups = \"drop\") %>%\n  summarise(\n    lowest_count = min(count),\n    lowest_date  = date_documented[which.min(count)],\n    highest_count = max(count),\n    highest_date  = date_documented[which.max(count)]\n  )\n\nglimpse(ufo_highest_lowest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1\nColumns: 4\n$ lowest_count  <int> 1\n$ lowest_date   <date> 2002-03-25\n$ highest_count <int> 1268\n$ highest_date  <date> 2009-12-12\n```\n\n\n:::\n:::\n\n\nThe lowest count of 1 during 2002 makes me think whether there are other data with a count of 1, but during a different year making both equally competent dates for the lowest range.\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_new %>%\n  mutate(date_documented = mdy(date_documented)) %>%\n  group_by(date_documented) %>%\n  summarise(count = n(), .groups = \"drop\") %>%\n  filter(count == min(count))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  date_documented count\n  <date>          <int>\n1 2002-03-25          1\n2 2003-01-20          1\n```\n\n\n:::\n:::\n\n\n\nIt turns out there are two dates - but the reason for 2002 showing up first is because it was parsed properly before hand itself.\n\nThis graph is plotted using the whole date - to make a bar graph or histogram we need to extract the year from the date. We will store this view format of viewing data as ufo_sightings_new1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_new1 <- ufo_sightings_new %>%\n  mutate(\n    date_time_parsed = mdy_hm(date_time),\n    date_only = as.Date(date_time_parsed),\n    time_only = format(date_time_parsed, \"%H:%M\"),\n    year = year(date_time_parsed)\n  )\nglimpse(ufo_sightings_new1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 66,516\nColumns: 14\n$ date_time        <chr> \"10/10/1949 20:30\", \"10/10/1956 21:00\", \"10/10/1960 2…\n$ city_area        <chr> \"san marcos\", \"edna\", \"kaneohe\", \"bristol\", \"norwalk\"…\n$ state            <chr> \"tx\", \"tx\", \"hi\", \"tn\", \"ct\", \"al\", \"fl\", \"ca\", \"nc\",…\n$ country          <chr> \"us\", \"us\", \"us\", \"us\", \"us\", \"us\", \"us\", \"us\", \"us\",…\n$ ufo_shape        <chr> \"cylinder\", \"circle\", \"light\", \"sphere\", \"disk\", \"dis…\n$ encounter_length <dbl> 2700, 20, 900, 300, 1200, 180, 120, 300, 180, 1800, 1…\n$ description      <chr> \"This event took place in early fall around 1949-50. …\n$ date_documented  <chr> \"4/27/2004\", \"1/17/2004\", \"1/22/2004\", \"4/27/2007\", \"…\n$ latitude         <dbl> 29.88306, 28.97833, 21.41806, 36.59500, 41.11750, 33.…\n$ longitude        <dbl> -97.94111, -96.64583, -157.80361, -82.18889, -73.4083…\n$ date_time_parsed <dttm> 1949-10-10 20:30:00, 1956-10-10 21:00:00, 1960-10-10…\n$ date_only        <date> 1949-10-10, 1956-10-10, 1960-10-10, 1961-10-10, 1965…\n$ time_only        <chr> \"20:30\", \"21:00\", \"20:00\", \"19:00\", \"23:45\", \"20:00\",…\n$ year             <dbl> 1949, 1956, 1960, 1961, 1965, 1966, 1966, 1968, 1968,…\n```\n\n\n:::\n:::\n\n\nLets parse the date_time and also seperate date and time - which might be useful to look at separately, and store them into ufo_sightings_new1\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_new1 <- ufo_sightings_withoutNA %>%\n  mutate(\n    date_time_parsed = mdy_hm(date_time),\n    date_only = as.Date(date_time_parsed),\n    time_only = format(date_time_parsed, \"%H:%M\"),\n    year = year(date_time_parsed)\n  )\n\nglimpse(ufo_sightings_new1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 66,516\nColumns: 15\n$ date_time                  <chr> \"10/10/1949 20:30\", \"10/10/1956 21:00\", \"10…\n$ city_area                  <chr> \"san marcos\", \"edna\", \"kaneohe\", \"bristol\",…\n$ state                      <chr> \"tx\", \"tx\", \"hi\", \"tn\", \"ct\", \"al\", \"fl\", \"…\n$ country                    <chr> \"us\", \"us\", \"us\", \"us\", \"us\", \"us\", \"us\", \"…\n$ ufo_shape                  <chr> \"cylinder\", \"circle\", \"light\", \"sphere\", \"d…\n$ encounter_length           <dbl> 2700, 20, 900, 300, 1200, 180, 120, 300, 18…\n$ described_encounter_length <chr> \"45 minutes\", \"1/2 hour\", \"15 minutes\", \"5 …\n$ description                <chr> \"This event took place in early fall around…\n$ date_documented            <chr> \"4/27/2004\", \"1/17/2004\", \"1/22/2004\", \"4/2…\n$ latitude                   <dbl> 29.88306, 28.97833, 21.41806, 36.59500, 41.…\n$ longitude                  <dbl> -97.94111, -96.64583, -157.80361, -82.18889…\n$ date_time_parsed           <dttm> 1949-10-10 20:30:00, 1956-10-10 21:00:00, …\n$ date_only                  <date> 1949-10-10, 1956-10-10, 1960-10-10, 1961-1…\n$ time_only                  <chr> \"20:30\", \"21:00\", \"20:00\", \"19:00\", \"23:45\"…\n$ year                       <dbl> 1949, 1956, 1960, 1961, 1965, 1966, 1966, 1…\n```\n\n\n:::\n:::\n\n### 2. UFO Shape count accross timeline\n\nFaceting the UFO shapes and plotting their counts over time.\n\n::: {.cell}\n\n```{.r .cell-code}\nsightings_per_year <- ufo_sightings_new1 %>%\n  group_by(year, ufo_shape) %>%\n  summarise(count = n(), .groups = \"drop\")\n\ngf_line(count ~ year, data = sightings_per_year, color = ~ufo_shape) %>%\n  gf_facet_wrap(~ufo_shape)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_line()`: Each group consists of only one observation.\nℹ Do you need to adjust the group aesthetic?\n`geom_line()`: Each group consists of only one observation.\nℹ Do you need to adjust the group aesthetic?\n`geom_line()`: Each group consists of only one observation.\nℹ Do you need to adjust the group aesthetic?\n`geom_line()`: Each group consists of only one observation.\nℹ Do you need to adjust the group aesthetic?\n`geom_line()`: Each group consists of only one observation.\nℹ Do you need to adjust the group aesthetic?\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n\nThis tells us that the pyramid, hexagon and changed ufo_shapes have almost no data. But there should exist atleast one data for it to be part of ufo_shape - so lets see how many is its count.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_new %>%\n  filter(ufo_shape %in% c(\"pyramid\", \"hexagon\", \"changed\")) %>%\n  count(ufo_shape)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  ufo_shape     n\n  <chr>     <int>\n1 changed       1\n2 hexagon       1\n3 pyramid       1\n```\n\n\n:::\n:::\n\n\nJust like predicted there is only 1 data in these ufo shape categories.\n\n### 3. UFO Shape count accross location\n\nWe created a cartograph — plotting each sighting by country to make a visual map of where the UFO sightings occurred\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_point(latitude ~ longitude, data = ufo_sightings_new1, color = ~ufo_shape, size = ~encounter_length) %>%\n  gf_labs(\n    x = \"Longitude\",\n    y = \"Latitude\",\n    color = \"UFO Shape\",\n    size = \"Encounter Length\",\n    title = \"UFO Sightings by Location\"\n  )\n```\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\nThe cartograph shows an overview of the sighting locations and UFO shapes. We can see that U.S. is highlighted prominently.\n\nNext, the data can be plotted by longitude and latitude while keeping the faceting by UFO shape, to check for possible patterns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngf_point(latitude ~ longitude, data = ufo_sightings_new1, color = ~ufo_shape) %>%\n  gf_facet_wrap(~ufo_shape) %>%\n  gf_labs(\n    x = \"Longitude\",\n    y = \"Latitude\",\n    color = \"UFO Shape\",\n    title = \"UFO Sightings by Shape\"\n  )\n```\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nThis plot shows the geographic distribution of UFO sightings by shape, helping us see where each type is reported.\n\nFaceting by shape highlights patterns or rare sightings that might be hidden in the overall dataset.\n\n### Encounter Length vs Latitude based on UFO shape\n\nVisualising encounter length instead of Latitude - just to check for interesting patterns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_new %>%\n  filter(!is.na(ufo_shape)) %>%\n  slice_sample(n = 150) %>%\n  gf_point(encounter_length ~ latitude | ufo_shape,\n           colour = ~ufo_shape,\n           size = 2) %>%\n  gf_labs(\n    title  = \"UFO Sightings Sample\",\n    x      = \"Latitude\",\n    y      = \"Encounter Length\",\n    colour = \"UFO Shape\"\n  )\n```\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n\nThis plot visualizes a random sample of UFO sightings, showing how encounter lengths vary with latitude for different shapes.\n\nFaceting by shape and coloring points highlights differences and patterns across UFO types in the sample.\n\n### 4. Reported UFO Sightings by Day\n\nIt would be interesting to check whether UFO sightings are more common on certain days of the week. A bar graph can help visualize this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_new %>%\n  count(weekday = wday(mdy_hm(date_time), label = TRUE)) %>%\n  gf_col(n ~ weekday, fill = \"orange\") %>%\n  gf_labs(title = \"Reported UFO Sightings by Day\", x = \"Day\", y = \"No of Reported Sightings\")\n```\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n*Saturday* has the most number of UFO sightings reported but it isn't exorbitantly high - but lets see a numeric representation for better understanding\n\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_byweek <- ufo_sightings_new1 %>%\n  mutate(weekday = wday(mdy_hm(date_time), label = TRUE)) %>%\n  count(weekday) %>%\n  arrange(match(weekday, c(\"Sun\", \"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\")))\n\nufo_sightings_byweek\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 2\n  weekday     n\n  <ord>   <int>\n1 Sun      9625\n2 Mon      8340\n3 Tue      8954\n4 Wed      9130\n5 Thu      9162\n6 Fri      9641\n7 Sat     11664\n```\n\n\n:::\n:::\n\n\n### 5. Reported UFO Sightings by Hours\n\nLets try doing the same but instead of days of week - we will try hours of week\n\n::: {.cell}\n\n```{.r .cell-code}\nufo_sightings_new %>%\n  count(hour = hour(mdy_hm(date_time))) %>%\n  gf_col(n ~ hour, fill = \"skyblue\") %>%\n  gf_labs(title = \"Reported UFO Sightings by Hour\", x = \"Hour\", y = \"No of Reported Sightings\")\n```\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n\n### 6. UFO Sightings by US States\n\nSince US is the biggest factor in ufo sightings - lets take each of US state and view its counts\n\n::: {.cell}\n\n```{.r .cell-code}\nus_sightings <- ufo_sightings_new1 %>%\n  filter(country == \"us\") %>%\n  count(state, sort = TRUE)\nglimpse(us_sightings)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 52\nColumns: 2\n$ state <chr> \"ca\", \"fl\", \"wa\", \"tx\", \"ny\", \"il\", \"az\", \"pa\", \"oh\", \"mi\", \"nc\"…\n$ n     <int> 8683, 3754, 3707, 3398, 2915, 2447, 2362, 2319, 2251, 1781, 1722…\n```\n\n\n:::\n:::\n\nVisualising this into bar graphs\n\n\n::: {.cell}\n\n```{.r .cell-code}\nus_sightings %>%\n  gf_col(n ~ state, fill = ~state) %>%\n  gf_labs(\n    title = \"UFO Sightings by US State\",\n    x = \"State\",\n    y = \"No of Reported Sightings\",\n    fill = \"State\"\n  ) \n```\n\n::: {.cell-output-display}\n![](ufo_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n\nThe states since they aren't abreviated are very congested but the state coded California has a exorbidantly high number of reportings - lets find its value\n\n\n::: {.cell}\n\n```{.r .cell-code}\nus_sightings %>%\n  filter(state == \"ca\") %>%\n  select(state, n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  state     n\n  <chr> <int>\n1 ca     8683\n```\n\n\n:::\n:::\n\n\n\nCalifornia has 8683 ufo sightings which we can see is pretty high compared to the rest of the states but lets find the mean, median and mode to get an accurate understanding\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- us_sightings$n\n\nsummary_table <- tibble(\n  Statistic = c(\"Mean\", \"Median\", \"Mode\"),\n  Value = c(mean(x), median(x), as.numeric(names(sort(table(x), decreasing = TRUE)[1])))\n)\n\nsummary_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  Statistic Value\n  <chr>     <dbl>\n1 Mean      1222.\n2 Median     798 \n3 Mode         7 \n```\n\n\n:::\n:::\n\n\nThe UFO sightings in CA is extremely high compared to all three mean, median and mode. So we can assume there is high delusion and hallucination rates in the state of California of the US.\n\n------------------------------------------------------------------------\n",
    "supporting": [
      "ufo_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}